### ISSUE TITLE
Bed renderer patching

### ISSUE THREAD

**Issue by RecompiledBirds** [RecompiledBirds/RimValiCore-RW#21]
Allow beds to change where a pawn is rendered.

**Comment by Danimineiro** [comment]
https://github.com/RecompiledBirds/RimVali-Core/blob/34fb03f2ca9c5f68bb109ea0e20d3aeffba2403e/Source/RimVali%20Core/2DBeds/HarmonyPatches.cs#L42

This needs to be started in the RenderPatch class itself, maybe with it's own harmony patcher
